#83 - ADS131M04 Driver
Northeastern-Electric-Racing/Embedded-Base pull request #108
Opened 2024-04-03 02:17 UTC by RChandler234

## Changes

The basic interface for the driver, setting up some basic SPI, and initializing the ADC into continuous-conversion mode using the WAKEUP command. Mainly trying to figure out whether I need to configure anything to get good readings from the ADC and the best 

## Notes
Notes for self from data sheet:
![image](https://github.com/Northeastern-Electric-Racing/Embedded-Base/assets/29521172/819f99ba-8704-4d08-b287-7cee682d44d4)
![image](https://github.com/Northeastern-Electric-Racing/Embedded-Base/assets/29521172/118157b8-3d75-4b0e-baf7-500b70f8d83d)

## Todo

- [ ] Make sure I'm writing the SPI commands in the right format
- [ ] Make sure everything is configured correctly to get good readings
- [ ] Implement functionality to read out of the ADC

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please reach out to your Project Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #83  (issue #)

2024-04-07 16:47 UTC, nwdepatie requested changes
Looks solid but you should prob add the actual code that does stuff lol

2024-04-07 16:47 UTC, nwdepatie commented on general/include/ADS131M04.h
> +} ads_config;
nit: Maybe change to `ads131_t`, might conflict with another similar chip

2024-04-07 16:47 UTC, nwdepatie commented on general/include/ADS131M04.h
> +#define UNLOCK_CMD 0x655
Add defines in C file to limit scope

2024-04-07 16:47 UTC, nwdepatie commented on general/include/ADS131M04.h
> +void ADS131M04_initialize(ltc_config *conf, SPI_HandleTypeDef *hspi, GPIO_TypeDef *hgpio, uint8_t cs_pin);
nit: stick with `lower_snake_case`

2024-04-07 16:47 UTC, nwdepatie commented on general/src/ADS131M04.c
> +// Method to abstract writing to a register, will use SPI commands under the hood
Nit: I like to use `/* this style */ ` for permanent comments

2024-04-07 16:47 UTC, nwdepatie commented on general/include/ADS131M04.h
> +uint8_t ADS131M04_read_ADC();
nit: add newline at end of file

2024-04-07 16:47 UTC, nwdepatie commented on general/src/ADS131M04.c
> +}
nit: add newline at end of file

2024-04-18 17:58 UTC, RChandler234 commented
![image](https://github.com/Northeastern-Electric-Racing/Embedded-Base/assets/29521172/3c23faea-bfdc-41c9-a2b9-d185d00960d5)

2024-06-04 21:16 UTC, nwdepatie approved these changes
Made some changes but looks god to me rn, we'll validate it when HV proteus board is assembled

2024-06-04 21:20 UTC, merged