Fixed eeprom drivers
Northeastern-Electric-Racing/Embedded-Base pull request #11
Opened 2023-10-01 01:11 UTC by Sabramz

EEPROM drivers now work with addresses instead of pages.

2023-10-01 21:11 UTC, Sabramz commented on general/src/m24c32.c
> -HAL_StatusTypeDef eeprom_page_erase(uint8_t page)
We don't have pages anymore, so I got rid of page_erase.

2023-10-01 21:14 UTC, Sabramz commented on general/src/m24c32.c
> +uint16_t check_size(uint16_t size)
Max read and write size is 32 bytes in one call, so if size > 32, return 32.

2023-10-01 21:14 UTC, Sabramz commented on general/src/m24c32.c
> +    for(int bytes_written = 0; bytes_written < size; bytes_written += 32)
Write in 32 byte batches. This is the same for the other functions.

2023-10-01 21:15 UTC, Sabramz commented on general/src/m24c32.c
> +        uint16_t write_size = check_size(size - bytes_written);
This is the size of the current write. Same for all functions.

2023-10-01 21:16 UTC, dyldonahue requested changes

2023-10-01 21:16 UTC, dyldonahue commented on general/src/m24c32.c
> -    else return M24C32_PAGE_SIZE - offset;
i dont think we need a max page size anymore. Technically we need to not overflow eeprom, but its so big that i think we can ignore it for now

2023-10-01 21:16 UTC, dyldonahue commented on general/src/m24c32.c
> +    for(int bytes_written = 0; bytes_written < size; bytes_written += 32)
why are we jumping 32 bytes? should be writing byte by byte

2023-10-01 21:16 UTC, dyldonahue commented on general/src/m24c32.c
> +        uint16_t write_size = check_size(size - bytes_written);
not sure i understand what we need check size for

2023-10-01 21:16 UTC, dyldonahue commented on general/src/m24c32.c
> +    for(int bytes_read = 0; bytes_read < size; bytes_read += 32)
same here as above, why +=32

2023-10-01 21:16 UTC, dyldonahue commented on general/src/m24c32.c
> +    for(int bytes_read = 0; bytes_read < size; bytes_read += 32)
ok i get it now, but think it unnecesarry. I think we should just read the number of bytes we want to, no need to account or 32 byte pages and read seperately

2023-10-07 22:40 UTC, Sabramz commented on middleware/src/eepromdirectory.c
> +#include "general/include/m24c32.h"
Does this file have access to m24c32.h?

2023-10-08 21:24 UTC, dyldonahue commented on middleware/src/eepromdirectory.c
> +#include "general/include/m24c32.h"
now it does

2023-10-08 21:24 UTC, dyldonahue approved these changes

2023-10-08 21:25 UTC, merged