Revamp yaml structure slightly
Northeastern-Electric-Racing/Embedded-Base pull request #126
Opened 2024-05-17 22:53 UTC by jr1221

## Changes

_Explanation of changes goes here_

## Notes

_Any other notes go here_

## Test Cases

- Case A
- Edge case
- ...

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please reach out to your Project Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2024-05-19 21:59 UTC, jr1221 commented
Additional changes
- Switched to bitstream_io for parsing bits, as it has dynamic sizing, signed support, and little/big endian support. I was running into some isssues decoding unsigned integers as little endian, and stumbled upon this library.  It is awesome because for the first time we can just specifiy what the bits are (big endian usually) without trying the architecture dependent swap bytes, `from_be`, etc.  Has same cpu usage as our own BitReader.
- For little endian, read a byte from the big endian stream as little endian.  This allows for per-point endianness in the library.  Defaults to big endian as that is most common on the can bus.

Additional verifications with this change
- Verified little endian decoding 
- Verified signed unsigned conversion at 16 and 32 bits at big and little endian

See the README for the list of limitations in writing CAN messages.  The biggest issue right now is signed messages must be full bytes, but tbh thats how everyone should be doing it imo.

2024-05-19 23:08 UTC, Peyton-McKee requested changes
I mean if it works it works. I personally feel like there must be a way to not have wrappers. But ig there was a reason i did it like that in the first place 🤷

2024-05-19 23:08 UTC, Peyton-McKee commented on cangen/README.md
> +        topic_append: false # (optional) whether to append the topic name with the value of the first CANPoint in points
yeah this is not a great solution to the problem. I would use :varName and then fill however many you have with however many can points you have.

2024-05-19 23:08 UTC, Peyton-McKee commented on cangen/README.md
> +|   └───CANPoint # a class which describes the decoding operations done to bits of a can message
this should be indented further

2024-05-19 23:08 UTC, Peyton-McKee commented on cangen/RustSynth.py
> +		# result.decode_data += RustSnippets.bitreader_impl
just delete this if were not gonna use it

2024-05-19 23:13 UTC, jr1221 commented on cangen/README.md
> +        topic_append: false # (optional) whether to append the topic name with the value of the first CANPoint in points
Ya that needs to improve.  Imo future PR?

2024-05-19 23:16 UTC, jr1221 commented on cangen/README.md
> +2. Use an existing formatter if possible.  To create a new one, add it to Format.py and RustSynth.py.  Name it what it does if it could be reused by unrelated functins (ex. divide by 100 --> divide10
But like there is no standard for each thing.  Some current can be divided by 100 and some can be divided by 1000, it really doesn't have any rhyme or reason.  So every time I go to use this I have to check the source code to see what it's doing and compare it to the documentation.

2024-05-19 23:27 UTC, Peyton-McKee commented on cangen/README.md
> +2. Use an existing formatter if possible.  To create a new one, add it to Format.py and RustSynth.py.  Name it what it does if it could be reused by unrelated functins (ex. divide by 100 --> divide10
I feel like the source code should match what this yaml says. Thats the point of the eventual c encoding framework

2024-05-19 23:28 UTC, Peyton-McKee commented on cangen/README.md
> +2. Use an existing formatter if possible.  To create a new one, add it to Format.py and RustSynth.py.  Name it what it does if it could be reused by unrelated functins (ex. divide by 100 --> divide10
were doing it backwards right now

2024-05-19 23:28 UTC, Peyton-McKee commented on cangen/README.md
> +        topic_append: false # (optional) whether to append the topic name with the value of the first CANPoint in points
yeah i mean ig. Its just the more data points we add the more well have to refactor

2024-05-19 23:35 UTC, jr1221 commented on cangen/README.md
> +        topic_append: false # (optional) whether to append the topic name with the value of the first CANPoint in points
Ya and I'm will to spend that time.  We only have a couple datapoints that may ever use this rn.

2024-05-19 23:35 UTC, jr1221 commented on cangen/README.md
> +        topic_append: false # (optional) whether to append the topic name with the value of the first CANPoint in points
Ya and I'm will to spend that time.  We only have a couple datapoints that may ever use this rn.

2024-05-20 15:15 UTC, dyldonahue commented on cangen/README.md
> +2. Use an existing formatter if possible.  To create a new one, add it to Format.py and RustSynth.py.  Name it what it does if it could be reused by unrelated functins (ex. divide by 100 --> divide10
leaning more towards peyton here. Why do we need to know what is actually happening, as long as we know the unit of the final result? like, do we care that its divided by 10k or 100, as long we know the final unit

2024-05-20 15:37 UTC, jr1221 commented on cangen/README.md
> +2. Use an existing formatter if possible.  To create a new one, add it to Format.py and RustSynth.py.  Name it what it does if it could be reused by unrelated functins (ex. divide by 100 --> divide10
Someone browsing the yaml could read the unit field and understand what the result is, we dont need a 2nd field describing that. For writing the yaml it is very annoying not knowing whats going on.  I was calling random things temperature because it divided by 10, and some things were called current when they weren't, etc.  I guess for literally every unit I could have a formatter, but then there could also be collisions between two things with different divisors that have the same unit.  Also the point of yaml is to not also have to edit rust source code. Plus I have to read the source code every time I use formatters to see what "current" does or "high_voltage". It saves me so much time to read remote source code or docs, see it should be divided by 10, and type divide10.  If I didn't read that I would scroll through a dozen formatters, check if "unit" exists, then check if it's dividing by the same thing.  

Additionally, if we start adding formatters that round or or wrap negatives or whatnot, we shouldn't just name them what they are for.  I picture formatters it like a code standard library, where you wouldn't name round to 2 decimal places "pedal_voltage" just because it is being used for the pedals.

Anyway that's just what I've been thinking on that.  I can change it back and use the old way it's only a couple minutes of writing I'm arguing over lol.

2024-05-21 02:02 UTC, Peyton-McKee commented on cangen/README.md
> +2. Use an existing formatter if possible.  To create a new one, add it to Format.py and RustSynth.py.  Name it what it does if it could be reused by unrelated functins (ex. divide by 100 --> divide10
well i think that acceleration should call a formatter that divides by ten you know what i mean. and so would current. If we ever wanted to change how all the currents were formatted we would just have to change this one formatter. Rather than going in and trying to find every single instance of where we use current and changing it to be divide by 100 or whatever

2024-05-21 02:04 UTC, Peyton-McKee commented on cangen/README.md
> +2. Use an existing formatter if possible.  To create a new one, add it to Format.py and RustSynth.py.  Name it what it does if it could be reused by unrelated functins (ex. divide by 100 --> divide10
i agree since right now we are not using the yaml for encoding, its annoying to have to go through the code and figure out whats going on. Once we have encoding. We should be standardizing how units are being formatted over mqtt and CAN via this. and having it describe what it actually is rather than what it is doing i think is the way to go. I was having a discussion about this at work on something similar. I think its fine either way. I personally prefer to views things from a conceptual level when writing code rather than a technical level

2024-05-21 05:19 UTC, jr1221 commented on cangen/README.md
> +2. Use an existing formatter if possible.  To create a new one, add it to Format.py and RustSynth.py.  Name it what it does if it could be reused by unrelated functins (ex. divide by 100 --> divide10
ALright well we can change it back in future c synth pr if we need.  There is a good chance however that if we do standardize we have to adhere to the standards of DTI and the charger box as they may do it differently than us.

2024-05-21 18:39 UTC, merged