Pca gpio expander
Northeastern-Electric-Racing/Embedded-Base pull request #127
Opened 2024-05-25 05:04 UTC by jr1221

Driver for pca gpio expander
https://www.ti.com/lit/ds/symlink/pca9539.pdf

My first ever driver so be very careful with this one lol.

2024-05-27 17:19 UTC, dyldonahue requested changes
very very good especially for first driver. Feel free to start on some of my comments before this, but i do need to take a look at the datasheet to check correctness on the port manipulation stuff, cuz it sorta felt funky but idk

2024-05-27 17:19 UTC, dyldonahue commented on general/src/pca9539.c
> +HAL_StatusTypeDef pca9539_read_pins(pca9539_t *pca, pca9539_reg_type_t reg_type, pca9539_port_t port, bool config[8])
the user is not gonna wanna interact with an array of bools - its okay to trust the user to decode an 8 bit register themselves. 

I would scrap the create and deconstruct buffer methods, since neither the user nor driver will want to interact with those, and adjust your methods to be read_pin and read_reg, where read_reg just fills an uint8 buffer with the byte read

2024-05-27 17:19 UTC, dyldonahue commented on general/src/pca9539.c
> +    *config = (data & (0b1 << pin)) > 0;
nitpick but 0b1 == decimal 1, so common convention here would be to scrap the 0b

2024-05-27 17:19 UTC, dyldonahue commented on general/src/pca9539.c
> +HAL_StatusTypeDef pca9539_write_pins(pca9539_t *pca, pca9539_reg_type_t reg_type, pca9539_port_t port, bool config[8])
same as for the reading functionality in pretty much everything. (scrap the bool array, refactor to be write_reg and write_pin)

2024-05-27 17:19 UTC, dyldonahue commented on general/src/pca9539.c
> +
am i blind or are we missing the init function definition here

2024-05-27 17:19 UTC, dyldonahue commented on general/src/pca9539.c
> +HAL_StatusTypeDef pca9539_write_pin(pca9539_t *pca, pca9539_reg_type_t reg_type, pca9539_port_t port, pca9539_pins_t pin, bool config)
another nit (because C will look at them the same anyway), but common practice is to work with uint8s for registers or pins. Its all semantic, but its good to reserve bools to logical "true or false", otherwise, high vs low, logical stuff like IO registers, its more common to work with uint8 or int8s,

2024-05-27 17:19 UTC, dyldonahue commented on general/src/pca9539.c
> +HAL_StatusTypeDef pca9539_write_pin(pca9539_t *pca, pca9539_reg_type_t reg_type, pca9539_port_t port, pca9539_pins_t pin, bool config)
to clarify, im referring to the config being a bool

2024-05-27 17:19 UTC, dyldonahue commented on general/include/pca9539.h
> +
Nitpick,  but i wanna start having a comment linking datsheet to IC drivers on the top of the header

2024-05-27 17:31 UTC, dyldonahue commented on general/include/pca9539.h
> +/// @brief Pin #, (0 through 7 on each bus, ex. bus 1 pin 3 is 13)
Should add macros for the registers we want to write to

![image](https://github.com/Northeastern-Electric-Racing/Embedded-Base/assets/98500199/52b57f75-61d8-4b62-b093-a8f40b2e7a41)

2024-05-27 17:36 UTC, jr1221 commented on general/src/pca9539.c
> +    return HAL_I2C_Mem_Write(pca->i2c_handle, pca->dev_addr << 1, address, I2C_MEMADD_SIZE_8BIT, data, sizeof(data), TIMEOUT);
The docs say you have to shift it then they add the write bit.

2024-05-27 17:36 UTC, dyldonahue commented on general/include/pca9539.h
> +typedef enum { PCA_B0, PCA_B1 } pca9539_port_t;
im not necesarily opposed, but in most cases, this would be consdiered a bit overkill for hw drivers. In reality, this is just toggling a 0 or 1 for register selection. The best way to do this, is to remove the enum, have the user pass in just a uint8 port num, and then select the register based on the port num, ie (if port == 0) reg = INPUT_PORT_0 (where the macro here should be added based on comment above.

2024-05-27 17:37 UTC, dyldonahue commented on general/src/pca9539.c
> +    PCA9539_DIRECTION = 6,
after looking at datasheet, im still a bit confused on what this is, im guessing its handling the registers, and if thats the case, this can be removed once the macros are added as described

2024-05-27 17:37 UTC, jr1221 commented on general/src/pca9539.c
> +HAL_StatusTypeDef pca9539_read_pins(pca9539_t *pca, pca9539_reg_type_t reg_type, pca9539_port_t port, bool config[8])
Alright will do.  Then its on the user (i.e. cerb) to deconstruct the buffer?

2024-05-27 17:39 UTC, dyldonahue commented on general/src/pca9539.c
> +    return HAL_I2C_Mem_Write(pca->i2c_handle, pca->dev_addr << 1, address, I2C_MEMADD_SIZE_8BIT, data, sizeof(data), TIMEOUT);
yeah the datasheet doesnt assume what HAL you are using, all i2c sheets will say that. But again, this is handled automatically by HAL. if we wrote our own HAL instead of using STM's, we would have to manually handle this

2024-05-27 17:41 UTC, jr1221 commented on general/src/pca9539.c
> +
Line 52

2024-05-27 17:41 UTC, dyldonahue commented on general/src/pca9539.c
> +HAL_StatusTypeDef pca9539_read_pins(pca9539_t *pca, pca9539_reg_type_t reg_type, pca9539_port_t port, bool config[8])
yep. If the user (cerb) wants the entire reg (which would be the case if they use this API instead of the single pin), its on them to do the bit shifting to extract the bit (s) they care about

2024-05-27 17:43 UTC, dyldonahue commented on general/include/pca9539.h
> +/// @brief Pin #, (0 through 7 on each bus, ex. bus 1 pin 3 is 13)
ie : #define INPUT_PORT_0 0x00

2024-05-27 17:45 UTC, jr1221 commented on general/include/pca9539.h
> +/// @brief Pin #, (0 through 7 on each bus, ex. bus 1 pin 3 is 13)
Could the macros instead be the pca9539_reg_type_t and it shows both ports?

2024-05-27 17:48 UTC, dyldonahue commented on general/src/pca9539.c
> +    pca->dev_addr = dev_addr << 1u; /* shifted one to the left cuz STM says so */
gonna guess that we dont need to shift this either, the user should jsut directly pass in one of the address macros and thats what we want passed into the HAL functions, no shifting necesary

2024-05-27 17:49 UTC, dyldonahue commented on general/src/pca9539.c
> +
got it, added a com

2024-05-27 17:51 UTC, dyldonahue commented on general/include/pca9539.h
> +/// @brief Pin #, (0 through 7 on each bus, ex. bus 1 pin 3 is 13)
not sure i see what u mean. technically because port 1 registers are always 1 higher than port 0 registers, you _can_ do something like (if port =1, reg += 1), but that doesnt simplify anything from (if port = 1, reg = REG_1_MACRO)

2024-05-27 18:19 UTC, jr1221 commented on general/src/pca9539.c
> +    pca->dev_addr = dev_addr << 1u; /* shifted one to the left cuz STM says so */
This is from docs.  I definitely should not have shifted it twice lol but I believe I should have once.
```
DevAddress – Target device address: The device 7 bits address value in datasheet must be shifted to the left before calling the interface
```

2024-05-28 22:41 UTC, dyldonahue approved these changes

2024-05-28 22:41 UTC, dyldonahue commented on general/include/pca9539.h
> +#define PCA_INPUT_0 0x00
nitpick but call them reg ( PCA_INPUT_1_REG

2024-05-28 22:41 UTC, dyldonahue commented on general/src/pca9539.c
> +#define TIMEOUT		  HAL_MAX_DELAY
remove, HAL delay is fine

2024-05-28 22:41 UTC, dyldonahue commented on general/src/pca9539.c
> +HAL_StatusTypeDef pca9539_read_reg(pca9539_t* pca, uint8_t reg_type, uint8_t config)
config should be named buf

2024-05-28 22:41 UTC, dyldonahue commented on general/src/pca9539.c
> +	uint8_t data_new = (data & ~(1u << pin)) | (config << pin);
remove u for 1u

2024-06-01 02:03 UTC, merged