Feature/highpass
Northeastern-Electric-Racing/Embedded-Base pull request #206
Opened 2024-11-24 20:11 UTC by rubennoro

-Implemented High Pass Algorithm with scale and alpha factors
-Code doesn't build because of issues with PCA driver code

_Any other notes go here_

## Test Cases

- Case A
- Edge case
- ...

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please reach out to your Project Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #178 (issue #178 )

2024-11-24 21:32 UTC, dyldonahue requested changes
I think the algorithm is good ( i dont have correct ones memorized by heart, but this seems roughly correct so i trust you sourced it well. 

only issueS

1. There isnt any room to add a new data point. The way this would likely to be used is that u create the filter, and can over time, add a new data point (ie, one more buffer). If done correctly, you shouldnt need to store the value of SAMPLES worth of data. Just the current data point, and the summation of the output up until this (prev_sum)

 
2. Right now, could only b used in one place/for one thing. Else, if you try and have two high pass filters, the data will combine and the static variables will belnd together.

the best solution is to create a high pass filter struct object, and instead of using statci variables, you store those as members of the struct, that way we can create multiple instances of the struct.

Id create a "high pass filter init" function that creates and returns a high pass filter object with a given alpha and scale, and the current "high_pass" API u have would just take in the new data point and the hgih pass object which should give access to the static data needed

2024-11-24 21:34 UTC, Sabramz requested changes

2024-11-24 21:34 UTC, Sabramz commented on general/include/pca9539.h
> +PCA 9539 16 bit GPIO expander.  Datasheet: https://www.ti.com/lit/ds/symlink/pca9539.pdf?ts=1716785085909
PCA changes shouldn't be in this PR

2024-11-24 21:34 UTC, Sabramz commented on middleware/include/high_pass.h
> +int high_pass(int alpha, int scale);
There are no functions for the user to pass a value through the filter.

2024-11-24 21:39 UTC, Sabramz requested changes

2024-11-24 21:39 UTC, Sabramz commented on middleware/src/high_pass.c
> +	static float prev_sum = 0.0;
This implementation does not allow for using multiple filters at once.

2024-11-24 21:39 UTC, Sabramz commented on middleware/src/high_pass.c
> +float high_pass(int alpha, int scale)
Should these values be ints? Floats might also be useful here.

2024-11-24 21:39 UTC, Sabramz commented on middleware/include/high_pass.h
> +int high_pass(int alpha, int scale);
Documentation for the function should be in the header file and use doxygen, javadoc style comments.

2024-11-24 21:39 UTC, Sabramz commented on middleware/src/high_pass.c
> +#define SAMPLES 12
Make this modifiable by the user. They should not have to edit code in embedded base. This also should be available to be edited on a per high-pass filter level.

2024-11-26 14:23 UTC, Sabramz commented on middleware/src/high_pass.c
> +	filter->alpha = alpha;
This is incorrect syntax and will not compile

2024-11-26 14:24 UTC, Sabramz requested changes

2024-11-26 14:24 UTC, Sabramz commented on middleware/src/high_pass.c
> +	filter->alpha = alpha;
This is incorrect syntax and will not compile

2024-12-05 17:23 UTC, Sabramz requested changes

2024-12-05 17:23 UTC, Sabramz commented on middleware/include/high_pass.h
> + */
Need to fill in doc comments

2024-12-21 04:09 UTC, Sabramz approved these changes

2024-12-21 04:12 UTC, Sabramz commented
Looks good. Merge after thorough testing.

2024-12-21 04:13 UTC, Sabramz commented
Outline the test cases tested in the header of this PR.

2025-02-01 03:23 UTC, closed without merging