[Debug] - Add timer start/stop notices
Northeastern-Electric-Racing/Embedded-Base pull request #208
Opened 2024-11-28 00:56 UTC by bjackson312006

## Changes
Added CAN message for timer start/stop notices in bms.json

## Checklist
- [ ] All commits are tagged with the ticket number
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes [#139](https://github.com/Northeastern-Electric-Racing/Shepherd-BMS/issues/139)

2024-11-28 01:56 UTC, jr1221 requested changes
One fix required with ID.  And ofc we need to test.

2024-11-28 01:56 UTC, jr1221 commented on cangen/can-messages/bms.json
> +        "id": "0x701",
This ID is already in use with https://github.com/Northeastern-Electric-Racing/Embedded-Base/blob/970cceb6d6589c23d21ff6e3d2c29696973902ff/cangen/can-messages/mpu.json#L291.  This issue is totally my fault, I didnt teach yall how to build the JSON (which would yield a compilation error).  Feel free to change to `6FF`

2024-11-30 21:00 UTC, jr1221 approved these changes
lgtm. merge when tested.

2025-01-05 23:09 UTC, jr1221 commented
Invert by doing tohex(2^fault_code)

2025-01-06 00:39 UTC, merged

2025-01-06 00:46 UTC, bjackson312006 commented
tested