ringbuffer + gitignore
Northeastern-Electric-Racing/Embedded-Base pull request #46
Opened 2023-12-16 00:49 UTC by dyldonahue

2023-12-16 14:02 UTC, nwdepatie requested changes
Some stuff to address

2023-12-16 17:30 UTC, nwdepatie requested changes
Some more stuff

2023-12-16 17:30 UTC, nwdepatie commented on middleware/include/ringbuffer.h
> +void* ringbuffer_dequeue(ringbuffer_t* rb, void* data);
Add in ringbuffer_destroy and keep naming consistent

2023-12-16 19:30 UTC, dyldonahue commented on middleware/include/ringbuffer.h
> +#endif // RINGBUFFER_H
lmao we dont talk about that

2023-12-16 19:33 UTC, dyldonahue commented on middleware/src/ringbuffer.c
> +    rb->buffer = (void**)malloc(capacity * sizeof(void*));
whoops this was a remnant of when i was doinf all at once good catch

2023-12-16 19:33 UTC, dyldonahue commented on middleware/src/ringbuffer.c
> +        free(rb->buffer[(rb->front + i) % rb->capacity]);
somehwat redundant since the count param should handle it but no harm to adding

2023-12-29 17:16 UTC, nwdepatie approved these changes
I think this looks good now, lets merge in to get shepherd shmovin

2024-01-01 22:34 UTC, merged