Creating eeprom_parition
Northeastern-Electric-Racing/Embedded-Base pull request #76
Opened 2024-02-18 23:45 UTC by bharath-v-m

## Changes

Included function for taking in array for structures for creating a partition

## Notes

_Any other notes go here_

## Test Cases

- Case A
- Edge case
- ...

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please reach out to your Project Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)
#70

2024-02-22 02:06 UTC, dyldonahue reviewed
Good start! definitely have the right idea, just a few things to fix up

2024-02-22 02:06 UTC, dyldonahue commented on middleware/src/eepromdirectory.c
> +/* taking in the number of user */
these objects dont need to be defined here - the user has to pass them in from their application

2024-02-22 02:06 UTC, dyldonahue commented on middleware/src/eepromdirectory.c
> +struct eeprrom_struct
This struct is already defined in the .h file - no need to define here

2024-02-22 02:06 UTC, dyldonahue commented on middleware/src/eepromdirectory.c
> +void eepromInit(int* eeprom_input, int& array_size)
this should be a pointer to the struct, not an int. Also, the array size will jsut be an int, no need for int&

2024-02-22 02:06 UTC, dyldonahue commented on middleware/src/eepromdirectory.c
> +    }
looks like there is a comment here showing the address calc, but doesnt look like its implemented.

2024-02-22 02:07 UTC, dyldonahue requested changes
Let me know if any of my comments dont make any sense

2024-02-22 23:57 UTC, bharath-v-m commented on middleware/src/eepromdirectory.c
> +/* taking in the number of user */
rectified.

2024-02-22 23:58 UTC, bharath-v-m commented on middleware/src/eepromdirectory.c
> +struct eeprrom_struct
removed it.

2024-02-22 23:58 UTC, bharath-v-m commented on middleware/src/eepromdirectory.c
> +void eepromInit(int* eeprom_input, int& array_size)
Understood. Changed it accordingly.

2024-02-25 23:12 UTC, dyldonahue requested changes
getting closer - a few small changes and this should be good to go

2024-02-25 23:12 UTC, dyldonahue commented on middleware/src/eepromdirectory.c
>  int *eeprom_input = new eeprom_struct(size_of_array);
this will come from the application, so we dont need to create the eeprom struct here. This file is only interface that applications use, so the input data will come from the applications. So, this line can be removed. 

(also side note: this is c++ syntax, in c, we have to use malloc() to dynamically allocate memory

2024-02-25 23:12 UTC, dyldonahue commented on middleware/src/eepromdirectory.c
> +    while (eeprom_data[i].id != NULL)
This is my fault because i didn't realize this until seeing them side by side - but this while loop can actually be incorporated directly into the for loop. Unlike the way it was in shepherd, this does not need to be a second, separate loop. Try to add the functionality of this while loop into the for loop above it

2024-02-25 23:12 UTC, dyldonahue commented on middleware/src/eepromdirectory.c
> +void eepromInit(struct* eeprom_input, int array_size)
the syntax for this parameter is not quite right. the struct is called eeprom_partition. see definition in the .h file. We want a pointer to this datatype passed in

2024-02-26 19:48 UTC, bharath-v-m commented on middleware/src/eepromdirectory.c
> +    while (eeprom_data[i].id != NULL)
I might be wrong here again, but i guess in the version I've uploaded the while condition for the address is in the for loop

2024-02-27 02:26 UTC, nwdepatie requested changes
Prob won't build, check my comments

2024-02-27 02:26 UTC, nwdepatie commented on middleware/include/eepromdirectory.h
> +void eepromInit(int* eeprom_input, int& array_size)
nit: incorrect naming convention, check other functions

2024-02-27 02:26 UTC, nwdepatie commented on middleware/include/eepromdirectory.h
> +void eepromInit(int* eeprom_input, int& array_size)
Will not build, & is not valid in C parameters iirc

2024-02-27 02:26 UTC, nwdepatie commented on middleware/include/eepromdirectory.h
> +void eeprom_read_data_index(uint8_t index, void *data);
nit: added whitespace

2024-02-27 02:26 UTC, nwdepatie commented on middleware/src/eepromdirectory.c
> +    {
nit: weird formatting, check other functions for curly brackets

2024-02-27 02:26 UTC, nwdepatie commented on middleware/src/eepromdirectory.c
> +    eeprom_input[i]->id = <id>;
Will not build, not sure on why <> was used

2024-02-27 02:26 UTC, nwdepatie commented on middleware/src/eepromdirectory.c
> +    eeprom_input[i]->size = <size>;
See above

2024-02-27 02:26 UTC, nwdepatie commented on middleware/src/eepromdirectory.c
> +    {
nit: curly bracket formatting not following convention

2024-02-27 21:57 UTC, nwdepatie requested changes
Incorrect operation (I think my bad cause I wrote it), also didn't address my comments in the header

2024-02-27 21:57 UTC, nwdepatie commented on middleware/src/eepromdirectory.c
> +        eeprom_data[i].address = eeprom_data[i-1].size - eeprom-data[i-1].address;
Uh I think that this should actually be + not -

2024-02-28 22:42 UTC, nwdepatie approved these changes
lgtm

2024-02-28 22:46 UTC, merged